language: node_js
node_js:
- 6.11.1
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@5.3.0
install:
- npm install
jobs:
  include:
  - stage: unit tests
    script:
    - npm run testunit
  - stage: unit tests
    script:
    - npm run testint
  - stage: deploying
    deploy:
      provider: heroku
      api_key:
        secure: N8v1HkjBiQF9TzkcPzs4V1Z8c/eYVKXWoBNHZ4dB/NEfkjqG2MjWMaCyzvw6stlEjcO1PB30pJEy6ZNQAYpKGHGXMpfTysT5DaboixYD3VlpM/GIGwB7Oqj37lQ/EzgcivTS/WMo32NavFtahSvxTdXOTFarvGSxSBQihxq+oHiFNGufCJH2V01xwg1YiRAfhcDcqjDfCgqobE87ZdgAI5D0iETrGlgeSU+q4dE9gcpWUfGEFUnycKUPo5Ksf+8FJatdHEaOTPL/idd0CvLJUf7ANygoas2CYuaPKQkkL/pHOdLTJleKYGtoelKp7a64dwoOnsP1Oe5qUG6mnomh+6OR5RcFoVG4Y+zsfjV+Y1Dc1ScF2vYTj9XYe6PxMGoRJjKCgyq9FlRuPEVH4HhuzgP4Y0aN4XVVDt/1SvFBmLrwZkv3fcxKxJO4L2CNLiRhSmauOs3tuQ0hfx9j9RWxmYnyred/uiIqw64P9KRsDj0ZfoRBwTIrUvuxQ6psasFq6YvFC3e8uS195H/AlEUjHZ0hhY8CGyaC9tz9554E6C+qENMGgeb9670a8MrBiDJWmWUBzmqRusGBOzNSRHae2I7OrP1Ukgyq0qXlkegEGoJHDfIIcNpzWmEjeduB8HDtVN+t3IpWZiIoov2rIHsVcUds/eUvwMhYfFPIADumlBA=
      app: travis-test
      on:
        repo: AleksandrRogachev94/travis-test
