language: node_js
node_js:
- 6.11.1
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@5.3.0
install:
- npm install
jobs:
  include:
  - stage: unit tests
    script:
    - npm run testunit
  - stage: unit tests
    script:
    - npm run testint
  - stage: deploying
    deploy:
      provider: heroku
      api_key:
        secure: hzW4k/cX6ONgtBPdgZMlhP4jFh+WR3z7KmxapW/7jrpcOa+iOUsfYHEK3iWz8mETGnqp09BSConFtEqIZLJRTj0ZXrfQlomEBLxc4JHLAezi5ZudQceGCMsS0J6JGLUSyFbqDycVFAOyicNJ0pzqx6sUo5h5dQvnykTBjto5zwa5PXkIqYeAycCucTJE902vYfXpx51VC3yp3sPWPJUbN9OXEdfb4H0IB1w9qvOV3KkyKf3pTxKKm1oEWb5lCdAPwyXGoEIpyV8SFy+LWlnXgZKdungh3olCwDVDJkacWyzmSovhhP3qPk1fFpPBU2ZMIJO9zAtlLFhp0SkJ5OnlqpDDwqee6i1pMZIjU6Ve9QoO9VBMMMPbQXV6Ne684Pj7bup22pXpAkxtek9FULOHXJXEfwUhxEqI91ineJD9j0J7pdu/9fY4m+DJaAmE6Pk05taHTF8wZFezuo2qMLlOJGABcpxGhMAAwUOFrLwfCnSoRe2CqcSy8GDRiWQTgX9v0dHX7BEbFCRMe1WdflUEn1ohDrgY3p86AkjzfFDWQp61Si2ZNUyOxx+j3KUp9N2NxxhjRMHOJ9uK5d/2cvHNRX4UoQRoe/UQ0Sw5vxSvYPjZTo3ks1b6EDs4tzPk5DxOvfp21TaassOY0xmsHRdaMrTrvMxPo/UbCA3qudp1rW4=
      app: travis-test
      on:
        repo: AleksandrRogachev94/travis-test
