language: node_js
node_js:
- 6.11.1
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@5.3.0
install:
- npm install
jobs:
  include:
  - stage: unit tests
    script:
    - npm run testunit
  - stage: unit tests
    script:
    - npm run testint
  - stage: deploying
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: TAJkZ++XiQS19wR3rkl/YtsVZH6vjxj8Me601fxJSl2Nth2XGUPod69aiULAe32rxv184I3Y3podmr4UM9QzKKBIXN4WRr03vhBs1lnpCfpdeS6f2toLfysaqT4Q0o2WWlX9Una8LlDBf791Sy69PWQESPm3m+c+2MNiUx2f1Zknl8rnyTiPeMSkQ+Zx2N6p71VAdny02i139ApFD7MCmWG7R2FAWApPM5Mx2nicZf/kTgCXdWpuI5J7vI7dGLR+2h9VLxsZ5Noe7I6Hi62sClgQO3qZn2XkFmEQBXwTcl/mP5HF4y6FSff6hqPyaYHk+hN9uzcF8jgPumqps23qxx5Z2hZUPIzUMGvtNTZUqUv0XcMZeTBlXVWz5j56E0edOdFO/PTF/qGn+BvOtM9Y1hJlhrUtLE/mLmaur3IOSQlKtjc0s7YEn3xNBrQFGSX2oBfOdNCM/y6oB7JH8Rk+VDbv0pQgrz3nlvHwsTKD57a+Pk9b0ecHHJA4dqs5Uiuz7Zp6Q1ezisU51Y1nUm7iMVtCDIDB7j/eF1aOII5a8PeYXeMAapgPaXYria8jQoHb8Lb2r3aSC+TRaLCZW21VEJLoG01YomUFw80ADaEUariQgGbSqGrnRXPJCBNXXvhwA2fdXWli2B83Y98IAvFZswTa9MIlN4Lt/APORNwBZMg=
      app: travis-test
      on:
        repo: AleksandrRogachev94/travis-test
