language: node_js
node_js:
  - "6.11.1"
cache:
  directories:
    - "node_modules"
before_install:
  - "npm i -g npm@5.3.0"
install:
  - "npm install"

jobs:
  include:
    - stage: unit tests
      script:
        - "npm run testunit"
    - stage: unit tests
      script:
        - "npm run testint"
