language: node_js
node_js:
- 6.11.1
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@5.3.0
install:
- npm install
jobs:
  include:
  - stage: unit tests
    script:
    - npm run testunit
  - stage: unit tests
    script:
    - npm run testint
  - stage: deploying
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: TvWXkKOrqyt2xJhy6K+i5MEgfh1AyFg2WrlLQ/riPnl9Ubzk2TRBeLq7zw4BrYt2qklaWwAJF2kCwaK42pqu4xKQM5Rnirjo0uEbWKbIFY1qroWUU6xzE4rMCIo+JCzJ5NWcVGlricVWN2NSJ2g5uSJr2E8Jngs1RqCGbWMKWNCvFh77d8zC9lmP6D0PJ1eAg0S1G3AeVzFilUO1nUBJhIk4sSNZ9sz6QZBVO1AThR9iTm/GWND2ITQ7OBvCWLUKENlC2QVwJxUr1G1KbLKFop/IXnWjOv8gekZIslM7sLMx0mU/NAT6WenYDYj6WZ5WCFQthCLBAnciuzWJEWTZZFs7xgKrSgNh23z83uj2wbo2WElGmUtD6lDuPB4yWAwXrNWWV2wUd85CBDubcarHWEcY+vyutk6bBSJje7Qnl8xKf1D9wAjUsa+lnpo5b8sm+Id+hInebPVUxpbEBsub340PCMgS5zmEl21OS6c3vWdozxdQ7Te7lmIHNyCAVa+TZoMd7mbNNIIeg7WuHO1zIeT8gxvRMiJQy7pudMYftTYucQqhW43Ggf0PMfmyaVP0N+Ec45H2dTVcfryFunKUYh+V433Zhfvd2ooUUouYvWnr/7Tg+h5b6ZnyzcmCB2G9Rh+I7kcsrg8eSeWB8XSaZATnJuBAmG+z/96DYewWOIM=
      app: travisteststaging
      on:
        repo: AleksandrRogachev94/travis-test
